### ISSUE TITLE
No such file or directory: '/src/models/v1-5-pruned.ckpt'

### ISSUE THREAD

**Issue by holwech** [rossjillian/cog-controlnet-11#2]
I'm trying to reuse your project but I just can't get it to work properly. I tried to run this repo without any modifications to the code (except downloading the models). I've tried to deploy this as-is to Replicate, tried to run it locally, but I keep getting the same error:

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/worker.py", line 185, in _setup
run_setup(self._predictor)
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/predictor.py", line 49, in run_setup
predictor.setup()
File "predict.py", line 33, in setup
self.canny_model = load_model(canny_model_name)
File "predict.py", line 243, in load_model
torch.load(os.path.abspath('./models/v1-5-pruned.ckpt'))
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
with _open_file_like(f, 'rb') as opened_file:
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/src/models/v1-5-pruned.ckpt'
ⅹ Model setup failed
```

The ckpt file is not found, even though it's there. I've tried different paths too but can't seem to find the correct one. How did you manage to get this to run in Replicate, or even locally? 

@rossjillian

**Comment by usamaehsan** [comment]
@holwech facing same issue, are you able to solve it?

**Comment by holwech** [comment]
I haven't yet, still looking into it. Will post here if I do (and I hope you do too!).
